# Run this job on pushes to `develop` (later; now pushes to update-docs).
name: "Build and deploy docs"

on:
  # Triggers the workflow on push but only for the indicated branches
  push:
    branches:
      - "update-docs"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Check lockfile
        run: poetry lock --check

      - name: Install packages
        run: poetry install --no-interaction --with docs




      - name: Build
        run:
          poetry run portray as_html --overwrite -o site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site # The folder the action should deploy.
          branch: gh-pages
          # target-folder: develop

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     branch: gh-pages
