# Simple workflow for deploying static content to GitHub Pages
# Run this job on pushes to `develop` (later; now pushes to update-docs).
name: "Build and deploy docs develop"

on:
  # Triggers the workflow on push but only for the indicated branches
  push:
    branches:
      - "develop"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Check lockfile
        run: poetry lock --check

      - name: Install packages
        run: poetry install --no-interaction --with docs

      - name: Build html
        run:
          poetry run mkdocs build -f ./docs/mkdocs.yml -d ../site

      - name: Setup git config
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Rename folder
        run: |
            echo "Renaming site folder and committing"
            git checkout gh-pages
            rm -r develop
            mv site develop
            git add develop/
            git commit -m "update docs for develop"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
