# Run this job on pushes to `develop`, and for pull requests. If you don't specify
# `branches: [develop], then this actions runs _twice_ on pull requests, which is
# annoying.
name: "Merge checks"

on:
  pull_request:
  push:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Style check with py311-ubuntu
            python: '3.11'
            arch: x64
            os: ubuntu-latest
            toxenv: style
          - name: Build doc check with py311-ubuntu
            python: '3.11'
            arch: x64
            os: ubuntu-latest
            toxenv: docs
          - name: Type check with py39-ubuntu
            python: '3.9'
            arch: x64
            os: ubuntu-latest
            toxenv: py39-typing
          - name: Type check with py310-ubuntu
            python: '3.10'
            arch: x64
            os: ubuntu-latest
            toxenv: py310-typing
          - name: Type check with py311-ubuntu
            python: '3.11'
            arch: x64
            os: ubuntu-latest
            toxenv: py311-typing
          - name: Test suite with py39-ubuntu
            python: '3.9'
            arch: x64
            os: ubuntu-latest
            toxenv: py39
          - name: Test suite with py310-ubuntu
            python: '3.10'
            arch: x64
            os: ubuntu-latest
            toxenv: py310
          - name: Test suite with py311-ubuntu
            python: '3.11'
            arch: x64
            os: ubuntu-latest
            toxenv: py311

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Check lockfile
        run: poetry lock --check

      - name: Install packages
        run: poetry install --no-interaction --no-root --only testrunner

      - name: Run tests
        run: poetry run tox -e ${{ matrix.toxenv }}

      - name: Report coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests
